### ISSUE TITLE
Automatic move not working / endTurn behavior

### ISSUE THREAD

**Issue by davqvist** [boardgameio/boardgame.io#952] opened 2021-06-30 16:20 UTC
I want to implement an autopass option for my game, but it behaves oddly. 

```
    pass: (G, ctx) => {
      return movePass( G, ctx );
    },
    passTurn: (G, ctx) => {
      G.players[ctx.currentPlayer].passed = true;
      return movePass( G, ctx );
    },

(...)

function movePass( G, ctx ){
(... bunch of stuff)

  ctx.events.endTurn();

(... bunch of stuff)
}
```
 The player has the option to either pass their turn or autopass (passTurn) until a specific phase is reached where in the phase onBegin the autopass gets reset
 
```
  G.players.forEach( function( player, id ){
    player.passed = false;
  });
```
In the turn onBegin I would like to autopass now.

```
   onBegin: (G, ctx) => {
      if( G.players[ctx.currentPlayer].passed ){
        movePass( G, ctx );
      }
    }
```
but it behaves very oddly that I really can't explain. It seems that it works the first time but if another player passes he passes like twice and the autopassing player is on the move again.
I can't change the turn order and exclude the player because the bunch of stuff in movePass needs to be executed regardless.
There is no moveLimit enabled.

Can anyone explain why this doesn't work or what I am doing incorrectly?

**Comment by delucis** [comment] 2021-07-05 11:02
I think this is a result of #526. We have a check to prevent more than one turn ending per action, so by definition it isn’t currently possible to end a turn from `onBegin` (because `onBegin` happens when a turn has just been ended).

So in your case, when `movePass` is called from `onBegin`, I’d guess it does “bunch of stuff” but won’t actually end the turn.

One option is to already set the new player when calling [the `endTurn` event](https://boardgame.io/documentation/#/events?id=endturn). You could iterate over the players, figure out who hasn’t passed and then call `endTurn({ next: playerWhoDidNotPass })`. Another variant of [this can be achieved using `turn.endIf`](https://boardgame.io/documentation/#/turn-order?id=ad-hoc).

**Comment by davqvist** [comment] 2021-07-05 11:18
That is unfortunate. Like I explained, your options don't really work for me, because the bunch of stuff needs to happen regardless no matter if autopass is enabled or not. So it is not that the player doesn't actually get their turn, they get their turn and I just want an automatic move to speed up the game which is passing. Is there no way to disable the check?

**Comment by delucis** [comment] 2021-07-05 11:48
> Is there no way to disable the check?

Not currently, unfortunately. Although I do think resolving #526 is a good idea when someone has the time.

I guess one approach would be:

1. Find the players who passed.
2. For each player who did, call a `bunchOfStuff` method that contains all the logic that has to always happen.
3. End the turn, setting the player who didn’t pass as `next`.
4. In `onBegin`, also call `bunchOfStuff`.

**Comment by davqvist** [comment] 2021-07-05 12:01
I will give it a try, but I feel this will get real messy. Especially as phases might change too.
Also I can think of plenty of other QOL improvements for my game where on a players turn there is only one move available with no choices to be made and the player has to make a move, it is taken automatically to speed up the game. It seems this currently can't be done easily if this automatic move ends the turn.

**Comment by delucis** [comment] 2021-07-05 12:44
> It seems this currently can't be done easily if this automatic move ends the turn.

Yeah, this would likely run into the same problem.

**Comment by delucis** [comment] 2021-07-14 09:29
Closing this as a duplicate of #526. Thanks for raising this issue, it’s always helpful to see different use cases.

**Closed by delucis** 2021-07-14 09:29 UTC
