### ISSUE TITLE
Phase is not properly updated ....

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#669] opened 2020-05-06 08:59 UTC
... in case of multiplayer running on Local. 
```
Deal = {
    name: "deal",
    turn: { moveLimit: 1 },
    setup: () => ({
      deal: deal(),
      bidding: [],
    }),
    phases,
  };

phases = {
  [PHASE_BIDDING]: {
    moves: { bid },
    endIf: (G) => {
      return  G.bidding.lenght === 10;
    },
    start: true,
    next: PHASE_DECLARE,
  },
  [PHASE_DECLARE]: { moves: playCard },
};

```

When G.bidding.length achieve length 10 then phase is finished ( i see that `ctx.phase` says `'PHASE_DECLARE'` however playCard move is not visible in moves and i see ` Uncaught TypeError: moves.playCard is not a function`. When i added `playCard` to the list of allowed moves of `PHASE_BIDDING` then i see `ERROR: disallowed move: playCard ERROR: move not processed - canPlayerMakeMove=false, playerID=[0]` Maybe it is because im running multiplayer game witj four client in one browser window, but up to documentation it is allowed.

**Comment by delucis** [comment] 2020-05-06 09:53
Thanks for the report. Do you think this could be for the same reason I outlined in my answer to #670?

If not, would you be able to share a CodeSandbox or other reproduction for us to test?

**Comment by delucis** [comment] 2020-07-16 14:58
Closing this due to lack of reproduction for now. Feel free to open with more details!

**Closed by delucis** 2020-07-16 14:58 UTC
