### ISSUE TITLE
Javascript error when mousing over the debug Logs

### ISSUE THREAD

**Issue by mrhappyasthma** [boardgameio/boardgame.io#625] opened 2020-04-19 04:18 UTC
I started a new project and have a basic flow between some phases. But if I mouse-over or click on an element in the debug `Log` tab, I see an error:

![error](https://user-images.githubusercontent.com/1547356/79679321-d292f280-81b9-11ea-8388-6e42e3beb5b8.JPG)

Any ideas on what might be going wrong? I'm not even sure where to look, based on the stack trace.

I would guess maybe the `ctx` is invalid somehow, but this all seems to be code in the underlying library and not calling into my code.

**Comment by nicolodavis** [comment] 2020-04-19 10:23
Hi @mrhappyasthma.  Would you be able to provide a CodeSandbox link that demonstrates this problem?

**Comment by delucis** [comment] 2020-07-16 15:00
Closing due to lack of reproduction for now. Feel free to reopen with more details!

**Closed by delucis** 2020-07-16 15:00 UTC
