### ISSUE TITLE
Dynamically determine if move is undoable + access if it is undoable in UI

### ISSUE THREAD

**Issue by on3iro** [boardgameio/boardgame.io#1047] opened 2022-01-14 20:21 UTC
Hey folks,

I basically have two questions:

1. What would be the best way to dynamically determine if a move is undoable. For example let's say that I have a generic `playEvent()` move, which might cause an Event to be played, which in return lets the user draw cards (which should be undoable). Is there a way to make this possible? Or is the recommended way to implement a move for every single entity (e.g. a card) and compose common logic? That way my would basically decide which of the multitude of moves should be called when a card has been played. I would like to avoid this. I would also need to drill tons of moves through my React-components, which also doesn't sound fun. (I probably would be able to combine some of them into some form of configuration prop, but still...)

2. Is there any means to determine if the last move is undoable? I did not find anything in the API. What I want to achieve is, that I only show and undo-button, if the move is indeed  undoable. Ofcourse I could write a flag into `G` but to me it feels like the API should be able to communicate this and writing into `G` would feel a bit redundant.

Thanks in advance :)

**Comment by delucis** [comment] 2022-01-14 20:58
Hi!

1. If I’ve understood correctly, the issue is that a generic move (the hypothetical `playEvent`) should be undoable in some circumstances, but not in others, right? This is possible, although I’m now seeing it’s not documented [in the Game API docs](https://boardgame.io/documentation/#/api/Game), nor in the Undo/Redo docs, which should be fixed! The long-form move syntax’s `undoable` property can be a function that returns a boolean:

    ```js
    const playEvent = {
      move: (G, ctx, ...args) => {
        // do some move logic
        // store if this should be undoable
        G.playEventUndoable = canUndo;
      },
      undoable: (G, ctx) => G.playEventUndoable,
    };
    ```
    
    The docs only show the static `undoable: false` type of usage, but the above works too.

2. No, this isn’t currently supported, although it would be a good idea to add it — would probably prompt us to extract the logic guarding undo/redos into a nice reusable form.

(One note about prop-drilling moves etc., I find this is can be a good place to use React’s context API: create a context that provides `moves` and then any component that needs to make a move can get it via the context without needing it drilled down to it.)

**Comment by on3iro** [comment] 2022-01-14 21:50
Hi @delucis 

thanks for the super quick answer.

Regarding 1.
Awesome: that was exactly what I was hoping for!

Regarding 2.
Yeah that would be great :) 

I also thought about introducing the context API into my game and will probably do so, as soon as I get the feeling, that prop drilling does no longer cut it.

Thanks again! :) 

Should I leave this issue open to document **2.** or should I rather open a new issue for this?

**Comment by delucis** [comment] 2022-01-14 21:52
A new issue which is clearly a feature request for point 2 would be super helpful. Thanks!

**Closed by delucis** 2022-01-14 21:52 UTC
